# 不要修改此文件
# DO NOT EDIT THIS FILE
import json
import flask
from flask import Flask, Response, request, jsonify
from optimize import optimizer

app = Flask(__name__)

@app.route('/optimize', methods=['POST'])
def optimize():
    containers = request.json.get("containers")
    accesslog_path = request.json.get("accesslog_path")
    cpu_limit = request.json.get("cpu_limit")
    memory_limit = request.json.get("memory_limit")
    ret = optimizer.optimize(containers, accesslog_path, cpu_limit, memory_limit)
    response = flask.make_response(jsonify(ret))
    return response

@app.route('/ready', methods=['GET'])
def ready():
    response = flask.make_response(optimizer.ready())
    response.status_code = 200
    return response

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=3001)